import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { 
  DollarSign, 
  Users, 
  TrendingUp, 
  Gift, 
  CheckCircle, 
  Clock,
  AlertCircle,
  Loader2
} from 'lucide-react';

const AffiliateProgram = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [loading, setLoading] = useState(true);
  const [affiliateStatus, setAffiliateStatus] = useState<any>(null);
  const [applicationNote, setApplicationNote] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    checkAffiliateStatus();
  }, []);

  const checkAffiliateStatus = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        navigate('/auth');
        return;
      }

      const { data, error } = await supabase
        .from('affiliates')
        .select('*')
        .eq('user_id', user.id)
        .maybeSingle();

      if (error) throw error;
      
      setAffiliateStatus(data);
      
      // If approved, redirect to dashboard
      if (data?.status === 'approved') {
        navigate('/affiliate-dashboard');
      }
    } catch (error) {
      console.error('Error checking affiliate status:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleApply = async () => {
    if (!applicationNote.trim()) {
      toast({
        title: 'Error',
        description: 'Please tell us why you want to join the affiliate program.',
        variant: 'destructive'
      });
      return;
    }

    setSubmitting(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { error } = await supabase
        .from('affiliates')
        .insert([{
          user_id: user.id,
          application_note: applicationNote,
          affiliate_code: '' // Will be auto-generated by trigger
        }]);

      if (error) throw error;

      toast({
        title: 'Application Submitted',
        description: 'Your application has been submitted for review. We\'ll notify you once it\'s processed.',
      });

      checkAffiliateStatus();
    } catch (error: any) {
      console.error('Error submitting application:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to submit application. Please try again.',
        variant: 'destructive'
      });
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50 to-pink-50 dark:from-slate-950 dark:via-purple-950/20 dark:to-slate-950 flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-purple-600" />
      </div>
    );
  }

  if (affiliateStatus?.status === 'pending') {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50 to-pink-50 dark:from-slate-950 dark:via-purple-950/20 dark:to-slate-950 py-12 px-4">
        <div className="container max-w-2xl mx-auto">
          <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border border-slate-200/50 dark:border-slate-700/50">
            <CardContent className="p-12 text-center">
              <div className="w-20 h-20 bg-gradient-to-r from-yellow-500 to-orange-600 rounded-full flex items-center justify-center mx-auto mb-6">
                <Clock className="w-10 h-10 text-white" />
              </div>
              <h2 className="text-3xl font-bold mb-4">Application Under Review</h2>
              <p className="text-slate-600 dark:text-slate-400 mb-6">
                Your affiliate application is currently being reviewed by our team. 
                We'll notify you via email once a decision has been made.
              </p>
              <Badge className="bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400 border-0">
                Pending Review
              </Badge>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  if (affiliateStatus?.status === 'rejected') {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50 to-pink-50 dark:from-slate-950 dark:via-purple-950/20 dark:to-slate-950 py-12 px-4">
        <div className="container max-w-2xl mx-auto">
          <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border border-slate-200/50 dark:border-slate-700/50">
            <CardContent className="p-12 text-center">
              <div className="w-20 h-20 bg-gradient-to-r from-red-500 to-pink-600 rounded-full flex items-center justify-center mx-auto mb-6">
                <AlertCircle className="w-10 h-10 text-white" />
              </div>
              <h2 className="text-3xl font-bold mb-4">Application Not Approved</h2>
              <p className="text-slate-600 dark:text-slate-400 mb-6">
                Unfortunately, your affiliate application was not approved at this time.
              </p>
              {affiliateStatus.rejection_reason && (
                <div className="bg-slate-100 dark:bg-slate-800 rounded-lg p-4 mb-6">
                  <p className="text-sm text-slate-700 dark:text-slate-300">
                    <strong>Reason:</strong> {affiliateStatus.rejection_reason}
                  </p>
                </div>
              )}
              <p className="text-sm text-slate-500 dark:text-slate-400">
                You can contact our support team if you have questions about this decision.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50 to-pink-50 dark:from-slate-950 dark:via-purple-950/20 dark:to-slate-950 py-12 px-4">
      <div className="container max-w-6xl mx-auto space-y-12">
        {/* Hero Section */}
        <div className="text-center space-y-4">
          <div className="inline-flex items-center gap-3 px-6 py-3 bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-950/30 dark:to-pink-950/30 rounded-2xl border border-purple-200/50 dark:border-purple-800/50">
            <Gift className="w-5 h-5 text-purple-600" />
            <span className="text-sm font-medium text-slate-700 dark:text-slate-300">Affiliate Program</span>
          </div>
          
          <h1 className="text-5xl font-bold bg-gradient-to-r from-slate-900 via-purple-800 to-pink-700 dark:from-white dark:via-purple-200 dark:to-pink-200 bg-clip-text text-transparent">
            Earn Money Sharing PitchSora
          </h1>
          <p className="text-xl text-slate-600 dark:text-slate-400 max-w-3xl mx-auto">
            Join our affiliate program and earn <strong>20% commission</strong> on every subscription you refer
          </p>
        </div>

        {/* Benefits Grid */}
        <div className="grid md:grid-cols-3 gap-6">
          <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border border-slate-200/50 dark:border-slate-700/50">
            <CardContent className="p-6 text-center">
              <div className="w-16 h-16 bg-gradient-to-r from-emerald-500 to-teal-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <DollarSign className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold mb-2">20% Commission</h3>
              <p className="text-slate-600 dark:text-slate-400">
                Earn 20% on every subscription sale you generate
              </p>
            </CardContent>
          </Card>

          <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border border-slate-200/50 dark:border-slate-700/50">
            <CardContent className="p-6 text-center">
              <div className="w-16 h-16 bg-gradient-to-r from-blue-500 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <Users className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold mb-2">Unlimited Referrals</h3>
              <p className="text-slate-600 dark:text-slate-400">
                No limits on how many people you can refer
              </p>
            </CardContent>
          </Card>

          <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border border-slate-200/50 dark:border-slate-700/50">
            <CardContent className="p-6 text-center">
              <div className="w-16 h-16 bg-gradient-to-r from-orange-500 to-red-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <TrendingUp className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold mb-2">Real-Time Tracking</h3>
              <p className="text-slate-600 dark:text-slate-400">
                Track your earnings and referrals in real-time
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Application Form */}
        <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border border-slate-200/50 dark:border-slate-700/50">
          <CardHeader>
            <CardTitle className="text-2xl">Apply to Join</CardTitle>
            <p className="text-slate-600 dark:text-slate-400">
              Tell us why you'd be a great affiliate partner
            </p>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <label className="text-sm font-medium mb-2 block">
                Why do you want to join our affiliate program?
              </label>
              <Textarea
                value={applicationNote}
                onChange={(e) => setApplicationNote(e.target.value)}
                placeholder="Tell us about your audience, marketing channels, and why you're interested in promoting PitchSora..."
                rows={6}
                className="resize-none"
              />
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-2">
                Applications are typically reviewed within 24-48 hours
              </p>
            </div>

            <Button 
              onClick={handleApply}
              disabled={submitting || !applicationNote.trim()}
              className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700"
            >
              {submitting ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Submitting...
                </>
              ) : (
                <>
                  <CheckCircle className="w-4 h-4 mr-2" />
                  Submit Application
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* How It Works */}
        <Card className="bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border border-slate-200/50 dark:border-slate-700/50">
          <CardHeader>
            <CardTitle className="text-2xl">How It Works</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex gap-4">
              <div className="w-10 h-10 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full flex items-center justify-center flex-shrink-0 text-white font-bold">
                1
              </div>
              <div>
                <h4 className="font-bold mb-1">Apply & Get Approved</h4>
                <p className="text-slate-600 dark:text-slate-400">
                  Submit your application and wait for approval from our team
                </p>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="w-10 h-10 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full flex items-center justify-center flex-shrink-0 text-white font-bold">
                2
              </div>
              <div>
                <h4 className="font-bold mb-1">Share Your Unique Link</h4>
                <p className="text-slate-600 dark:text-slate-400">
                  Get your personalized referral link and start sharing it with your audience
                </p>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="w-10 h-10 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full flex items-center justify-center flex-shrink-0 text-white font-bold">
                3
              </div>
              <div>
                <h4 className="font-bold mb-1">Earn Commissions</h4>
                <p className="text-slate-600 dark:text-slate-400">
                  Earn 20% commission on every subscription purchased through your link
                </p>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="w-10 h-10 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full flex items-center justify-center flex-shrink-0 text-white font-bold">
                4
              </div>
              <div>
                <h4 className="font-bold mb-1">Get Paid</h4>
                <p className="text-slate-600 dark:text-slate-400">
                  Request payouts once you reach the minimum balance threshold
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default AffiliateProgram;
