
-- Add 5 more complete classic templates
INSERT INTO resume_templates (name, description, category, json_content, template, styles, is_premium) VALUES
('Minimalist Classic', 'Ultra-clean design with maximum white space and subtle lines', 'classic',
'{"theme":{"primaryColor":"#0f172a","secondaryColor":"#64748b","accentColor":"#94a3b8","backgroundColor":"#ffffff","textColor":"#1e293b","fontFamily":"Inter, sans-serif"},"sections":[{"type":"header","id":"header","style":{"padding":"44px 50px","backgroundColor":"#ffffff","borderBottom":"1px solid #e2e8f0"}},{"type":"summary","id":"summary","style":{"padding":"32px 50px"}},{"type":"experience","id":"experience","style":{"padding":"32px 50px","borderTop":"1px solid #f1f5f9"}},{"type":"grid","id":"bottom-grid","style":{"display":"grid","gridTemplateColumns":"1fr 1fr","gap":"50px","padding":"32px 50px","borderTop":"1px solid #f1f5f9"},"children":[{"type":"skills","id":"skills"},{"type":"education","id":"education"}]}]}'::jsonb,
'{}'::jsonb, '{}'::jsonb, false),

('Traditional Sidebar', 'Classic two-column layout with left sidebar for contact info', 'classic',
'{"theme":{"primaryColor":"#1e293b","secondaryColor":"#475569","accentColor":"#64748b","backgroundColor":"#ffffff","textColor":"#0f172a","fontFamily":"Arial, sans-serif"},"sections":[{"type":"columns","id":"main-layout","style":{"display":"grid","gridTemplateColumns":"280px 1fr","minHeight":"297mm"},"children":[{"type":"sidebar","style":{"backgroundColor":"#f1f5f9","padding":"40px 28px","borderRight":"2px solid #cbd5e1"},"children":[{"type":"header","id":"sidebar-header","style":{"marginBottom":"32px"}},{"type":"skills","id":"skills","style":{"marginBottom":"32px"}},{"type":"education","id":"education"}]},{"type":"main","style":{"padding":"40px"},"children":[{"type":"summary","id":"summary","style":{"marginBottom":"32px"}},{"type":"experience","id":"experience"}]}]}]}'::jsonb,
'{}'::jsonb, '{}'::jsonb, false),

('Formal Document', 'Document-style resume with clear hierarchy and structure', 'classic',
'{"theme":{"primaryColor":"#0f172a","secondaryColor":"#475569","accentColor":"#64748b","backgroundColor":"#ffffff","textColor":"#111827","fontFamily":"Georgia, serif"},"sections":[{"type":"header","id":"header","style":{"padding":"32px 45px","backgroundColor":"#ffffff","borderBottom":"4px solid #0f172a"}},{"type":"summary","id":"summary","style":{"padding":"28px 45px","backgroundColor":"#fafafa"}},{"type":"experience","id":"experience","style":{"padding":"28px 45px"}},{"type":"grid","id":"bottom-grid","style":{"display":"grid","gridTemplateColumns":"2fr 1fr","gap":"40px","padding":"28px 45px","borderTop":"2px solid #e5e7eb"},"children":[{"type":"education","id":"education"},{"type":"skills","id":"skills","style":{"backgroundColor":"#fafafa","padding":"20px","borderRadius":"4px"}}]}]}'::jsonb,
'{}'::jsonb, '{}'::jsonb, false),

('Banking Professional', 'Conservative design with green accents perfect for financial sector', 'classic',
'{"theme":{"primaryColor":"#064e3b","secondaryColor":"#047857","accentColor":"#10b981","backgroundColor":"#ffffff","textColor":"#1f2937","fontFamily":"Arial, sans-serif"},"sections":[{"type":"header","id":"header","style":{"padding":"38px 40px","backgroundColor":"#f8fafb","borderTop":"6px solid #065f46"}},{"type":"summary","id":"summary","style":{"padding":"28px 40px","borderLeft":"4px solid #10b981","backgroundColor":"#f0fdf4","margin":"0 40px 28px"}},{"type":"experience","id":"experience","style":{"padding":"28px 40px"}},{"type":"grid","id":"bottom-grid","style":{"display":"grid","gridTemplateColumns":"1fr 1fr","gap":"40px","padding":"28px 40px","backgroundColor":"#f9fafb"},"children":[{"type":"skills","id":"skills"},{"type":"education","id":"education"}]}]}'::jsonb,
'{}'::jsonb, '{}'::jsonb, false),

('Refined Elegance', 'Sophisticated design with burgundy accents and refined typography', 'classic',
'{"theme":{"primaryColor":"#7f1d1d","secondaryColor":"#991b1b","accentColor":"#b91c1c","backgroundColor":"#ffffff","textColor":"#1f2937","fontFamily":"Georgia, serif"},"sections":[{"type":"header","id":"header","style":{"padding":"40px","backgroundColor":"#fef2f2","borderBottom":"3px solid #7f1d1d","textAlign":"center"}},{"type":"summary","id":"summary","style":{"padding":"32px 50px","textAlign":"center","fontStyle":"italic","borderBottom":"1px solid #fee2e2"}},{"type":"experience","id":"experience","style":{"padding":"32px 50px"}},{"type":"grid","id":"bottom-grid","style":{"display":"grid","gridTemplateColumns":"1fr 1fr","gap":"40px","padding":"32px 50px","backgroundColor":"#fef2f2"},"children":[{"type":"education","id":"education"},{"type":"skills","id":"skills"}]}]}'::jsonb,
'{}'::jsonb, '{}'::jsonb, false);
